-- CreateEnum
CREATE TYPE "PROFILE_STATUS" AS ENUM ('ACTIVE', 'DISABLED');

-- AlterTable
ALTER TABLE "Customer" ADD COLUMN     "status" "PROFILE_STATUS" NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE "SellerProfile" ADD COLUMN     "status" "PROFILE_STATUS" NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE "Staff" ADD COLUMN     "status" "PROFILE_STATUS" NOT NULL DEFAULT 'ACTIVE';
